### PR TITLE
add ex_mustang

### PR DESCRIPTION
**Pull request by techgaun**
I would like to add this one. This is not just a responder but also a bot but I guess it fits on Responders category as it is mostly responders that make ExMustang

### CODE REVIEW

**Comment by enilsen16** [comment]
Hmmm... How would you feel about an open source bot section instead?

**Comment by techgaun** [comment]
@enilsen16 yeah that would be better for sure. Should I update this PR to have _Open Source Bots_ section and put ExMustang over there?

**Comment by enilsen16** [comment]
Yeah that would be awesome. Please put the new section in-between responders and resources.
Thanks @techgaun

**Comment by techgaun** [comment]
@enilsen16 updated. please review. thanks!

**Comment by enilsen16** [comment]
👍

**Pull request merged**
